const DATABASES = [
  {
    name: 'AR0000DATA',
    tables: [
      { name: "ARCard", notes: "No data." },
      { name: "ARCompany", notes: "Contains just contact info for Legacy Liquor." },
      { name: "ARCurrency", notes: "No data." },
      { name: "ARCustomer", notes: "Customer data, such as Customer ID, name, phone, acct open date, credit limit, price group, etc." },
      { name: "ARCustomerType", notes: "No data." },
      { name: "ARDeletedInvoice", notes: "No data." },
      { name: "ARDeletedPayment", notes: "No data." },
      { name: "ARGLTxn", notes: "No data." },
      { name: "ARInvoice", notes: "Customer invoices, with data such as customer ID, amount, etc." },
      { name: "ARInvoiceDetail", notes: "Invoice details. Not many columns here, just line number, amount, “for amount”, and a few others." },
      { name: "ARLog", notes: "Seem to be admin logs." },
      { name: "ARNextID", notes: "A table that holds values for the next ID value for customer, invoice, invoice number and payment." },
      { name: "ARPayment", notes: "Payment info for different customers, including amounts and dates." },
      { name: "ARPaymentDetail", notes: "Table linking payments to invoices." },
      { name: "ARPaymentDistribute", notes: "A table containing payment id, line number, payment amount." },
      { name: "ARProfile", notes: "Seems to contain some minor config data" },
      { name: "ARRecurringInvoice", notes: "No data." },
      { name: "ARRecurringInvoiceDetail", notes: "No data." },
      { name: "ARSalesRep", notes: "No data." },
      { name: "ARSecurity", notes: "No data." },
      { name: "ARShipVia", notes: "No data." },
      { name: "ARStore", notes: "No data." },
      { name: "ARTemplate", notes: "No data." },
      { name: "GLChartofAcct", notes: "No data." },
      { name: "GLDept", notes: "No data." },
    ],
  },
  {
    name: 'FDDATA',
    tables: [
      { name: "FDAwardType", notes: "No data." },
      { name: "FDCompany", notes: "Contains just contact info for Legacy Liquor." },
      { name: "FDProfile", notes: "Seems to contain minor config data." },
      { name: "FDSecurity", notes: "Seems to contain minor config data." },
      { name: "FDStore", notes: "Contains just the store name (Legacy)" },
      { name: "FDTxnPoint", notes: "Transaction history for some sort of store points, along with remarks" },
    ],
  },
  {
    name: 'PSCUSTOMER',
    tables: [
      { name: "Customer", notes: "Customer info, such as name, contacts, etc. Very messy and incomplete." },
      { name: "CustomerDemographic", notes: "No data." },
      { name: "CustomerSearchKey", notes: "No data." },
      { name: "CustomerType", notes: "No data." },
      { name: "DemographicChoice", notes: "No data." },
      { name: "DemographicDef", notes: "No data." },
      { name: "DisallowedTender", notes: "No data." },
      { name: "FDCard", notes: "Contains just one customer ID." },
      { name: "PSNextID", notes: "No data." },
      { name: "SearchKeyDef", notes: "No data." },
    ],
  },
  {
    name: 'PSDATA',
    tables: [
      { name: "PSAccessSystem", notes: "Contains six abbreviations and their descriptions." },
      { name: "PSBackupServer", notes: "No data." },
      { name: "PSFont", notes: "Font settings." },
      { name: "PSMessage", notes: "No data." },
      // { name: "PSUser", notes: "User IDs, passwords, first and last names for 10 users." },
      { name: "PSUserSystem", notes: "Access config for the 10 users from PSUser table." },
    ],
  },
  {
    name: 'PSGIFTCARD',
    tables: [
      { name: "GCCardType", notes: "Contains two gift card types." },
      { name: "GCCompany", notes: "Contains just contact info for Legacy Liquor." },
      { name: "GCGiftCard", notes: "Contains gift card data with dollar value, issue date, etc." },
      { name: "GCProfile", notes: "Basic config for gift cards (expiry period, language code, etc)." },
      { name: "GCSecurity", notes: "Different gift card actions and action levels." },
      { name: "GCStore", notes: "No data." },
      { name: "GCTxnDetail", notes: "Gift card transaction details." },
    ],
  },
  {
    name: 'RS0000CUSTOMER',
    tables: [
      { name: "ProfitekSystem", notes: "Contains one config row." },
      { name: "RSCustomer", notes: "Contains lots of customer information, including financials such as purchase totals and credit limits. Much of the data is incomplete, though." },
      { name: "RSCustomerCity", notes: "No data." },
      { name: "RSCustomerContact", notes: "Contact info for 22 customers." },
      { name: "RSCustomerDel", notes: "Seems to contain data on deleted customers, with dates as well as customer ID and names." },
      { name: "RSCustomerPrefer", notes: "No data." },
      { name: "RSCustomerProvince", notes: "Abbreviations and names for 13 Canadian provinces and territories." },
      { name: "RSCustomerSubcategory", notes: "No data." },
      { name: "RSCustomerType", notes: "Contains five different customer types." },
    ],
  },
  {
    name: 'RS0000DATA',
    tables: [
      { name: 'ProfitekSystem', notes: "Contains one config row." },
      { name: 'RSAirMilesDetail', notes: "No data." },
      { name: 'RSAirMilesOffer', notes: "Some descriptions of Air Miles offers." },
      { name: 'RSAPVendor', notes: "Vendor information, including contacts and financials." },
      { name: 'RSAPVendorType', notes: "No data." },
      { name: 'RSARRequest', notes: "Looks like some transaction data, with amounts, customer IDs, employee 'IDs', etc." },
      { name: 'RSAWItemBonusPoints', notes: "Item code, start/end dates, and bonus points." },
      { name: 'RSAWItemPointsExempt', notes: "Item code, start/end dates." },
      { name: 'RSAWItemRedemptionPoints', notes: "No data." },
      { name: 'RSBarcode', notes: "Barcode, item code, size code, color code, width code." },
      { name: 'RSCashierClosing', notes: "3 closing times for cashiers." },
      { name: 'RSCashierClosingTender', notes: "No data." },
      { name: 'RSCashierClosingTenderDetail', notes: "No data." },
      { name: 'RSCashPickup', notes: "No data." },
      { name: 'RSCashValue', notes: "Tender type ID, description, face value." },
      { name: 'RSCategory', notes: "List of categories, probably different product/transaction categories." },
      { name: 'RSCCACreditRequest', notes: "Credit requests, presumably by customers." },
      { name: 'RSCCACreditRequestBak', notes: "No data." },
      { name: 'RSCCAEncryptFail', notes: "No data." },
      { name: 'RSCCAProfile', notes: "Config related to banking and payments." },
      { name: 'RSCCASummary', notes: "No data." },
      { name: 'RSCCAWorkStation', notes: "WSCode numbers 1-7." },
      { name: 'RSColor', notes: "One row for color code “IPA”." },
      { name: 'RSCommVol', notes: "No data." },
      { name: 'RSCompanyInfo', notes: "Contains just contact info for Legacy Liquor." },
      { name: 'RSCPInvoice', notes: "No data." },
      { name: 'RSCPInvoiceDetail', notes: "No data." },
      { name: 'RSCPInvoiceTxnDetail', notes: "No data." },
      { name: 'RSCPVendor', notes: "No data." },
      { name: 'RSCUPBatchClose', notes: "No data." },
      { name: 'RSCUPRequest', notes: "No data." },
      { name: 'RSCurrency', notes: "Lists two currencies, CDN and USD." },
      { name: 'RSDailyClose', notes: "No data." },
      { name: 'RSDeposit', notes: "Some sort of customer transaction data." },
      { name: 'RSDiscountType', notes: "Discount types, one for 100%, one for 10%, rest for 0%." },
      { name: 'RSEmail', notes: "No data." },
      // { name: 'RSEmployee', notes: "Employee IDs, names, passwords, and other info." },
      { name: 'RSEspGCLog', notes: "No data." },
      { name: 'RSEvent', notes: "Event info containing descriptions, start/end dates." },
      { name: 'RSEventDays', notes: "Event day related info, including start/end times." },
      { name: 'RSEventHoliday', notes: "No data." },
      { name: 'RSExpenseType', notes: "Expense type IDs from 1-15." },
      { name: 'RSGLChartofAcct', notes: "No data." },
      { name: 'RSGLDept', notes: "Only one entry, GLDeptNum 000." },
      { name: 'RSGLJournalDay', notes: "No data." },
      { name: 'RSHCMessage', notes: "No data." },
      { name: 'RSImExOrderDownloadLog', notes: "No data." },
      { name: 'RSImExParameter', notes: "Some sort of key-value config." },
      { name: 'RSImExTask', notes: "No data." },
      { name: 'RSInvAdjustCostDetail', notes: "Cost adjustments, contains item code, qty, cost, modified 'cost', item description, inv record ID." },
      { name: 'RSInvAdjustCostHead', notes: "Seems to contain adjustments to invoices or inventory, with 'data' about invoice date and source txn ID." },
      { name: 'RSInvAdjustDetail', notes: "Adjustment details, containing audit ID, line, item code, qty, 'cost', item description and other columns." },
      { name: 'RSInvAdjustHead', notes: "More adjustment data." },
      { name: 'RSInventory', notes: "Inventory data, containing record ID, item code, serial number, qty, 'cost', source and source txn ID, as well as other columns. No descriptions or other data like 'that'." },
      { name: 'RSInventoryCount', notes: "No data." },
      { name: 'RSInventoryHold', notes: "No data." },
      { name: 'RSInventoryTrack', notes: "Seems to track inventory, and contains record ID, item code, 'cost', qty, inv record ID, and other columns." },
      { name: 'RSInvModExpiryDateLotNumDetail', notes: "No data." },
      { name: 'RSInvModExpiryDateLotNumHead', notes: "No data." },
      { name: 'RSInvModSerialStatusDetail', notes: "No data." },
      { name: 'RSInvModSerialStatusHead', notes: "No data." },
      { name: 'RSInvPCCountDetail', notes: "Not sure what this table contains, but columns are: PCID, post 'index', item code, description, cost and qty, as well as others." },
      { name: 'RSInvPCHead', notes: "Not sure about this table, columns are PCID and others." },
      { name: 'RSInvPCImageDetail', notes: "Not sure about this table, columns are PCID, item code, 'description', image qty, image cost, count qty, count cost, and others." },
      { name: 'RSInvRecDetail', notes: "audit ID, line, item code, item description, unit code, qty, cost, 'local' cost, landed cost, price, markup, GP, inv record ID, and others." },
      { name: 'RSInvRecDetailMisc', notes: "" },
      { name: 'RSInvRecHead', notes: "" },
      { name: 'RSInvRecMoreDetail', notes: "" },
      { name: 'RSInvSptCmbDetail', notes: "" },
      { name: 'RSInvSptCmbHead', notes: "" },
      { name: 'RSInvTxfDetail', notes: "" },
      { name: 'RSInvTxfDetailMore', notes: "" },
      { name: 'RSInvTxfHead', notes: "" },
      { name: 'RSInvTxfHeadMisc', notes: "" },
      { name: 'RSInvTxfInventoryDetail', notes: "" },
      { name: 'RSItem', notes: "" },
      { name: 'RSItemCostChange', notes: "" },
      { name: 'RSItemDel', notes: "" },
      { name: 'RSItemFinishedProduct', notes: "" },
      { name: 'RSItemListTypeChange', notes: "" },
      { name: 'RSItemMergeLog', notes: "" },
      { name: 'RSItemPicture', notes: "" },
      { name: 'RSItemPriceChange', notes: "" },
      { name: 'RSItemRegion', notes: "" },
      { name: 'RSItemsAttrib', notes: "" },
      { name: 'RSItemSizeColor', notes: "" },
      { name: 'RSItemSizeColorPic', notes: "" },
      { name: 'RSItemSizeWidth', notes: "" },
      { name: 'RSItemStatus', notes: "" },
      { name: 'RSItemStockLevel', notes: "" },
      { name: 'RSItemsWebAttrib', notes: "" },
      { name: 'RSItemsWebAttribDefValue', notes: "" },
      { name: 'RSItemTicket', notes: "" },
      { name: 'RSItemUpdateLog', notes: "" },
      { name: 'RSItemVendor', notes: "" },
      { name: 'RSItemVendorRegion', notes: "" },
      { name: 'RSKitItem', notes: "" },
      { name: 'RSLabelSetting', notes: "" },
      { name: 'RSLayDetail', notes: "" },
      { name: 'RSLayHeader', notes: "" },
      { name: 'RSLayShip', notes: "" },
      { name: 'RSLinkItem', notes: "" },
      { name: 'RSLockTable', notes: "" },
      { name: 'RSMainButtons', notes: "" },
      { name: 'RSNextID', notes: "" },
      { name: 'RSNextIDDelPool', notes: "" },
      { name: 'RSOEAllocateExcept', notes: "" },
      { name: 'RSOETxnDetail', notes: "" },
      { name: 'RSOETxnDetailMore', notes: "" },
      { name: 'RSOETxnHeader', notes: "" },
      { name: 'RSOETxnShip', notes: "" },
      { name: 'RSOpenDrawerLog', notes: "" },
      { name: 'RSOrderTrack', notes: "" },
      { name: 'RSOthTxnCheck', notes: "" },
      { name: 'RSOthTxnCheckDetail', notes: "" },
      { name: 'RSParameter', notes: "" },
      { name: 'RSPKCOrderDetail', notes: "" },
      { name: 'RSPKCOrderHeader', notes: "" },
      { name: 'RSPKCOrderTxf', notes: "" },
      { name: 'RSPKCPickupDetail', notes: "" },
      { name: 'RSPKCPickupHeader', notes: "" },
      { name: 'RSPKCRefundOrder', notes: "" },
      { name: 'RSPriceMap', notes: "" },
      { name: 'RSPrintForm', notes: "" },
      { name: 'RSReason', notes: "" },
      { name: 'RSRegion', notes: "" },
      { name: 'RSRoyalDetail', notes: "" },
      { name: 'RSRoyalFee', notes: "" },
      { name: 'RSRoyalHeader', notes: "" },
      { name: 'RSSalesButtons', notes: "" },
      { name: 'RSSalesCommission', notes: "" },
      { name: 'RSSecGroupFns', notes: "" },
      { name: 'RSSecGroups', notes: "" },
      { name: 'RSSecGroupUsers', notes: "" },
      { name: 'RSSecSystemFnGroups', notes: "" },
      { name: 'RSSecSystemFns', notes: "" },
      { name: 'RSSecSystems', notes: "" },
      { name: 'RSSerialNumberChangeLog', notes: "" },
      { name: 'RSShift', notes: "" },
      { name: 'RSShipMethod', notes: "" },
      { name: 'RSSizeMatrix', notes: "" },
      { name: 'RSSizeMatrixDetail', notes: "" },
      { name: 'RSSpiff', notes: "" },
      { name: 'RSSplitItem', notes: "" },
      { name: 'RSSSBillCoupon', notes: "" },
      { name: 'RSSSBillDiscount', notes: "" },
      { name: 'RSSSBillSpecialPrice', notes: "" },
      { name: 'RSSSCoupon', notes: "" },
      { name: 'RSSSCouponItem', notes: "" },
      { name: 'RSSSCumuQtyDisc', notes: "" },
      { name: 'RSSSCumuQtyDiscItem', notes: "" },
      { name: 'RSSSCumuQtyDiscJoin', notes: "" },
      { name: 'RSSSCumuQtyDiscJoinDetail', notes: "" },
      { name: 'RSSSCustomerSpecial', notes: "" },
      { name: 'RSSSCustomerSpecialMarkup', notes: "" },
      { name: 'RSSSDiscount', notes: "" },
      { name: 'RSSSMixMatch', notes: "" },
      { name: 'RSSSPriceBreak', notes: "" },
      { name: 'RSSSPurchaseLimit', notes: "" },
      { name: 'RSSSSpecialPrice', notes: "" },
      { name: 'RSSSTopNQtySpecial', notes: "" },
      { name: 'RSSTMainBarFnButton', notes: "" },
      { name: 'RSSTMoreFnButton', notes: "" },
      { name: 'RSStore', notes: "" },
      { name: 'RSSTSalesButtonLayout', notes: "" },
      { name: 'RSSTSalesMenuLayout', notes: "" },
      { name: 'RSSTTenderBarFnButton', notes: "" },
      { name: 'RSSubcategory', notes: "" },
      { name: 'RSTax', notes: "" },
      { name: 'RSTaxArea', notes: "" },
      { name: 'RSTenderType', notes: "" },
      { name: 'RSTerms', notes: "" },
      { name: 'RSTxnDetail', notes: "" },
      { name: 'RSTxnDetailDelLog', notes: "" },
      { name: 'RSTxnDetailForeign', notes: "" },
      { name: 'RSTxnDetailInventory', notes: "" },
      { name: 'RSTxnDiscount', notes: "" },
      { name: 'RSTxnExpenseDtl', notes: "" },
      { name: 'RSTxnHeader', notes: "" },
      { name: 'RSTxnHeaderForeign', notes: "" },
      { name: 'RSTxnPayment', notes: "" },
      { name: 'RSTxnReason', notes: "" },
      { name: 'RSTxnShipping', notes: "" },
      { name: 'RSTxnTender', notes: "" },
      { name: 'RSTxnTenderForeign', notes: "" },
      { name: 'RSUserDrawer', notes: "" },
      { name: 'RSUserProfile', notes: "" },
      { name: 'RSWidth', notes: "" },
      { name: 'RSWorkstation', notes: "" },
      // { name: 'RSWorkStationLog', notes: "" },
    ],
  },
  {
    name: 'RS0000HISTORY',
    tables: [
      { name: "RSCashierClosingTender", notes: "" },
      { name: "RSCashierClosingTenderDetail", notes: "" },
      { name: "RSCashPickup", notes: "" },
      { name: "RSCCACreditRequest", notes: "" },
      { name: "RSCCASummary", notes: "" },
      { name: "RSCUPBatchClose", notes: "" },
      { name: "RSCUPRequest", notes: "" },
      { name: "RSDailyClose", notes: "" },
      { name: "RSGLJournal", notes: "" },
      { name: "RSSalesCommission", notes: "" },
      { name: "RSTxnDeletedDetail", notes: "" },
      { name: "RSTxnDetail", notes: "" },
      { name: "RSTxnDetailForeign", notes: "" },
      { name: "RSTxnExpenseDtl", notes: "" },
      { name: "RSTxnHeader", notes: "" },
      { name: "RSTxnHeaderForeign", notes: "" },
      { name: "RSTxnPayment", notes: "" },
      { name: "RSTxnReason", notes: "" },
      { name: "RSTxnShipping", notes: "" },
      { name: "RSTxnTender", notes: "" },
      { name: "RSTxnTenderForeign", notes: "" },
      { name: "RSAirMilesDetail", notes: "" },
      { name: "RSOpenDrawerLog", notes: "" },
      { name: "ProfitekSystem", notes: "" },
      { name: "RSARRequest", notes: "" },
      { name: "RSCashierClosing", notes: "" },
    ],
  },
  {
    name: 'RS0000PODATA',
    tables: [
      { name: "POHeader", notes: "" },
      { name: "POParameter", notes: "" },
      { name: "PORemark", notes: "" },
      { name: "POShipToAddress", notes: "" },
      { name: "ProfitekSystem", notes: "" },
      { name: "POCompanyInfo", notes: "" },
      { name: "PODetail", notes: "" },
      { name: "PODetailSize", notes: "" },
    ],
  },
  {
    name: 'RS0000WNDATA',
    tables: [
      { name: "RSWNFormSubcategory", notes: "" },
      { name: "RSWNItemImportSubcatMatch", notes: "" },
      { name: "RSWNParameter", notes: "" },
      { name: "RSWNPeriodMonth", notes: "" },
      { name: "RSWNPeriodTask", notes: "" },
      { name: "RSWNPeriodTaskInvRange", notes: "" },
      { name: "RSWNPeriodTaskSalesRange", notes: "" },
      { name: "RSWNPeriodYear", notes: "" },
      { name: "RSWNRentalItem", notes: "" },
      { name: "ProfitekSystem", notes: "" },
      { name: "RSWNBatchReport", notes: "" },
      { name: "RSWNFormCustType", notes: "" },
    ],
  },
]


// Export all queries in one object
module.exports = DATABASES
